### PR TITLE
Website redesign 

### PR DESCRIPTION
**Pull request by eirizarry**
Large PR which includes entire website redesign as we start looking to advertise more features about WorldWind. 

Includes: 

- new header, sticky footer
- responsiveness to large screen sizes
- new images that serve as heading backgrounds
- refactored examples and tutorials layout
- new web header and footer
- converted ESA logo to svg 
- created and applied new layout for all sections
- increased font-size

### CODE REVIEW

**Comment by pdavidc** [comment]
@endiairizarry This looks very good to me.

One thing: Several page footers (i.e. Web, About, Contact) are placed below the bottom of my viewport. Is this the intended design, or an indication that the footer placement needs more adjustment?

**Comment by eirizarry** [comment]
Yes, this was intentional. I placed a wrapper class around the entire body with a min-height 100% so that I could pin the footer to the bottom regardless of the screen's height or width.

**Comment by pdavidc** [comment]
To be clear, the footer is initially not visible. The top of the footer is aligned with the bottom of the viewport, so a scroll down is required to see the footer.

**Comment by eirizarry** [comment]
Yes, that's correct, I'm looking into how to fix it now.

**Comment by eirizarry** [comment]
@pdavidc Footer issue should be fixed now.

**Pull request merged**
