### PR TITLE
Replace jumbotron with responsive carousel slides

### PR DESCRIPTION
**Pull request by eirizarry**
Cycles through the jumbotron images rather than remaining static. Changes to static image for mobile devices

Added 
- smaller jpg files 
- replaced sliding carousel with fade effect
- for mobile devices, carousel is hidden and static starfield image is put in place. 

QA tested in Chrome, Firefox, and Safari.

### CODE REVIEW

**Comment by eirizarry** [comment]
@pdavidc, yes intentional because it looks better than just a plain black background, and I didn't want any overpowering image. The jpeg images in the desktop view are not good quality for mobile. I can swap out the image for now, but I've also been learning how to implement mobile design, so improvements are sure to follow.

**Comment by PJHogan** [comment]
The background images on the webpages are ridiculously dark. The Earth is not a pretty place at all!

**Comment by PJHogan** [comment]
Give us "overpowering imgaes" please!

**Comment by eirizarry** [comment]
@PJHogan @pdavidc I changed the brightness of the images. Let me know if these work or if you would like new screenshots.

**Comment by pdavidc** [comment]
@eirizarry Based on the feedback we got from @PJHogan, I suspect we'll need different images.

**Comment by emxsys** [comment]
The new background images are definitely better. I have few suggestions that might further improve the impact of the page banners:

**Suggestion 1:**
Include a banner showing _map_ content in 3D  (e.g. topographic/contours or OpenStreetMap) to express the versatility of the WorldWind visualizations.

**Suggestion 2:**
Add a banner to the About page.  This page is the first item in the menu and its arguably the most important page to non-developers and potential users/stakeholders.  And it's the driest page of the lot.  An appropriate banner for the intended audience would help. It need not be a screenshot in my opinion.

**Pull request merged**
